version: "3.4"

services:
  meoapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 55555:80
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
